from .ModularBBOBProblem import ModularBBOBProblem
from .ModularNonBBOBProblem import ModularNonBBOBProblem
from .ModularNonBBOBProblemWithSubspace import ModularNonBBOBProblemWithSubspace
from .ModularNonBBOBProblemWithDistance import ModularNonBBOBProblemWithDistance
from .ModularNonBBOBProblemWithPerturbedDistance import ModularNonBBOBProblemWithPerturbedDistance
from .Generalized_Gallagher_Functions.Generalized_Gallagher_Function_with_repetitions import GeneralizedGallagherFunctionWithRepetitions
from .Generalized_Gallagher_Functions.Generalized_Gallagher_Function import GeneralizedGallagherFunction